### ISSUE TITLE
Could not find option for key :arhive_path.

### ISSUE THREAD

**Issue by passionHan** [richardszalay/fastlane-plugin-act#4]
When I use act, always this error
`Could not find option for key :arhive_path. Available keys: ipa, archive_path, iconset, plist_file, plist_values, plist_commands, app_name, temp_dir, skip_delete_icons`

**I used it like this**
```
    act(
    archive_path: "../build/text.ipa",
    iconset: "../build/AppText.appiconset",
    )
```

**Comment by richardszalay** [comment]
Hi there,

It looks like you've uncovered a bug, albeit indirectly. Your issue is that your `archive_path` doesn't exist. The bug in act is that it throws the error you see when the archive doesn't exist because of a typo in the library.

I'll look at fixing the typo, but you'll still need to check the location of your archive.

Thanks for letting me know!

Richard
